[bar.default]
background_opacity = 0.61999998614192009
font_scale = 0.74999999068677425
padding = 13
scale = 1.1500000096857548
thickness = 22

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 0.46999998949468136
enabled = true
icon_size = 36
item_spacing = 0
launcher_position = "start"
position = "left"
radius = 8
show_dots = true

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 768.0
    cy = 718.4000244140625
    output = "eDP-1"
    placement_height = 864.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
app_icon_colorize = true
corner_radius_scale = 0.0

    [shell.animation]
    speed = 2.0000000298023224

    [shell.launcher]
    app_grid = true
    compact = true
    show_app_actions = true

[theme]
builtin = "Gruvbox"
community_palette = "Miasma"
source = "community"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "foot", "kitty", "niri" ]
    community_ids = [ "spicetify", "obsidian", "prismlauncher", "steam", "fastfetch" ]

[wallpaper.default]
path = "/nix/store/cnrvi9bczf7gl9y7hpi2nv3iy717zpa2-noctalia-5.0.0/share/noctalia/assets/noctalia-wallpaper.png"

[wallpaper.last]
path = "/nix/store/cnrvi9bczf7gl9y7hpi2nv3iy717zpa2-noctalia-5.0.0/share/noctalia/assets/noctalia-wallpaper.png"
