pub mod capability;
pub mod config;
pub mod fs;
pub mod inventory;
pub mod palette;
pub mod paths;
pub mod profile;
pub mod resolve;
pub mod state;

pub use capability::{Cadence, Capability, CapabilityClaim, CapabilityPlan, build_plan};
pub use config::{ApplicationContract, LibrarySelection, ThemeBundle};
pub use inventory::{
    AppearanceInventory, AppearanceLibrary, LibraryItem, LibraryKind, LibrarySelectionStatus,
};
pub use palette::Palette;
pub use profile::{Profile, ResolvedRole, ResolvedTheme};

pub const GENERATED_MARKER: &str = "Generated by theme-manager. Do not edit manually.";
