use crate::ResolvedTheme;
use anyhow::Result;
use serde::Serialize;
use std::path::PathBuf;

pub const GENERATED_MARKER: &str = "Generated by theme-manager. Do not edit manually.";

#[derive(Debug, Clone, Serialize)]
pub struct Artifact {
    pub path: PathBuf,
    pub contents: String,
}

pub trait Target: Send + Sync {
    fn id(&self) -> &str;
    fn output_paths(&self) -> Result<Vec<PathBuf>>;
    fn render(&self, theme: &ResolvedTheme) -> Result<Vec<Artifact>>;
}
