[accessibility]
ui_scale = 0.95000000670552254

[backdrop]
blur_intensity = 0.14999999664723873
enabled = true
tint_intensity = 0.59999998658895493

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.0
    capsule = true
    capsule_padding = 5.0
    capsule_radius = 0
    capsule_thickness = 0.99999998137354851
    center = [ "bar", "group:g1", "nightlight", "theme" ]
    concave_edge_corners = false
    contact_shadow = true
    end = [ "media", "tray", "notifications", "clipboard", "volume", "brightness", "control-center", "session" ]
    font_family = "Lilex Nerd Font Medium"
    font_scale = 1.019999984651804
    margin_edge = 7
    margin_ends = 150
    padding = 0
    panel_overlap = 0
    radius = 0
    scale = 0.85000000521540642
    shadow = true
    smart_auto_hide = false
    start = [ "wallpaper", "bar_2", "keybinds", "bluetooth", "battery", "workspaces", "privacy" ]
    thickness = 18
    widget_spacing = 4

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "date", "clock" ]
        opacity = 0.0
        padding = 5.0
        radius = 0.0

[control_center]
width = 900

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000007",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000009",
    "desktop-widget-000000000000000a",
    "desktop-widget-0000000000000008"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 864.0
    box_width = 848.0
    cx = 2184.0
    cy = 716.0
    flip_y = true
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = -3.1415927410125732
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        background_opacity = 1.0
        bands = 128
        centered = false
        color_1 = "primary"
        color_2 = "secondary"
        mirrored = false
        reversed = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 512.0
    box_width = 960.0
    cx = 552.0
    cy = 204.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = 0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = false
        description = "coming soon."
        font_family = "Unifont Japanese"
        opacity = 0.69000000000000006
        shadow = false
        title = "Its blud story"

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 1680.0
    box_width = 2976.0
    cx = 2464.0
    cy = 972.0
    flip_y = true
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = -0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background = false
        bar_width = 0.69999999999999996
        bloom_intensity = 0.90000000000000002
        fade_when_idle = true
        inner_diameter = 0.0
        ring_opacity = 1.0
        rotation_speed = 0.20000000000000001
        secondary_color = "tertiary"
        sensitivity = 0.80000000000000004
        visualization_mode = "bars_rings"
        wave_thickness = 0.69999999999999996

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 80.0
    box_width = 1552.0
    cx = 1792.0
    cy = 1040.0
    flip_x = true
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = false
        bands = 128
        centered = false
        color_1 = "tertiary"
        color_2 = "secondary"
        mirrored = false
        reversed = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 80.0
    box_width = 1552.0
    cx = 256.0
    cy = 1044.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000009.settings]
        background = false
        bands = 128
        centered = false
        color_1 = "secondary"
        color_2 = "primary"
        mirrored = false
        reversed = false
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-000000000000000a]
    box_height = 928.0
    box_width = 800.0
    cx = 2440.0
    cy = 916.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = 0.0
    type = "sticker"

        [desktop_widgets.widget.desktop-widget-000000000000000a.settings]
        background = false
        background_opacity = 1.0
        background_padding = 0
        background_radius = 0
        image_path = "/home/zap/Pictures/Memes/sajid-removebg-preview.png"
        opacity = 1.0

[dock]
active_monitor_only = true
background_opacity = 0.0
cross_axis_padding = 0
enabled = true
icon_size = 38
inactive_opacity = 0.60999998636543751
item_spacing = 4
magnification_scale = 2.0
main_axis_padding = 0
position = "left"
radius = 80
shadow = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 2400.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 1800.0

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[location]
address = "GrandPrairie TX"
sunrise = "07:30"
sunset = "20:30"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-4", "lockscreen-login-box@DP-3" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 1279.9998779296875
    cy = 878.00006103515625
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 898.0
    output = "DP-4"
    placement_height = 1080.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
force = false
temperature_day = 8400
temperature_night = 1600

[notification]
background_opacity = 0.48999998904764652

[osd]
background_opacity = 0.47999998927116394

    [osd.kinds]
    nightlight = false

[plugins]
enabled = [
    "ahmedhossamdev/sticky-notes",
    "kenn/keybind-cheatsheet",
    "noctalia/wallpaper_depth",
    "dunarand/tmux-provider",
    "cleboost/ssh-launcher",
    "zap/theme-manager"
]

[shell]
corner_radius_scale = 0.0
font_family = "Lilex Nerd Font"
lang = "en"
settings_window_translucent = true
time_format = "{:%I:%M %p}"

    [shell.animation]
    speed = 4.0

    [shell.launcher]
    app_grid = true
    compact = true

        [shell.launcher.providers.emoji]
        global = false

        [shell.launcher.providers.session]
        global = false

        [shell.launcher.providers.wallpaper]
        global = false

        [shell.launcher.providers.windows]
        global = false

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "glass"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screen_corners]
    size = 1

    [shell.shadow]
    alpha = 0.51999998837709427

[theme]
builtin = "Noctalia"
community_palette = "Monochrome"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "foot", "kitty", "niri", "starship" ]
    community_ids = [
        "spicetify",
        "pywalfox-beta4",
        "discord",
        "blender",
        "gimp",
        "obsidian",
        "prismlauncher",
        "steam",
        "fastfetch",
        "obs",
        "fzf",
        "tmux",
        "yazi"
    ]

[wallpaper]
directory = "/home/zap/Pictures/Wallpapers"
transition = []

    [wallpaper.automation]
    interval_seconds = 15

    [wallpaper.default]
    path = "/home/zap/Pictures/Wallpapers/lazyname/wallhaven-8oeg9y.jpg"

    [wallpaper.last]
    path = "/home/zap/Pictures/Wallpapers/lazyname/wallhaven-8oeg9y.jpg"

    [wallpaper.monitors.DP-3]
    path = "/home/zap/Pictures/Wallpapers/lazyname/wallhaven-8oeg9y.jpg"

    [wallpaper.monitors.DP-4]
    path = "/home/zap/Pictures/Wallpapers/lazyname/wallhaven-8oeg9y.jpg"

[widget.audio_visualizer]
anchor = true
bands = 128
capsule = true
capsule_opacity = 0.0
capsule_padding = 0
interactive = false
mirrored = false
width = 1227

[widget.bar]
type = "ahmedhossamdev/sticky-notes:bar"

[widget.bar_2]
type = "noctalia/wallpaper_depth:bar"

[widget.clock]
anchor = true
capsule = true
capsule_opacity = 0.0
capsule_padding = 48
capsule_radius = 80
format = "{:%I:%M %p}"
scale = 0.94999999999999996

[widget.keybinds]
type = "kenn/keybind-cheatsheet:keybinds"

[widget.nightlight]
capsule = true
capsule_opacity = 0.0

[widget.privacy]
capsule = true
capsule_opacity = 0.0

[widget.theme]
type = "zap/theme-manager:theme"


[widget.workspaces]
active_pill_size = 6.1500000000000004
capsule_padding = 0
font_scale = 1.01
hide_when_empty = true
inactive_pill_size = 2.1000000000000001
scale = 0.94999999999999996
show_labels = false
